### ISSUE TITLE
Keep the searching history, is it possible?

### ISSUE THREAD

**Issue by seeyou2n1ght** [kazuki-sf/ChatGPT_Extension#2]

**Comment by dandv** [comment]
This project is extremely simple: it [opens](https://github.com/kazuki-sf/ChatGPT_Extension/blob/main/popup.html#L10) https://chat.openai.com/chat in a popup. It does absolutely nothing else (why it exists, beats me; it's basically a bookmark).

So it's not possible to keep any history.

**Comment by kazuki-sf** [comment]
Thanks for clarifying, @dandv :)
