### ISSUE TITLE
why need permission for "Read and change data" on "cn.bing.com" 

### ISSUE THREAD

**Issue by rajpratik71** [kazuki-sf/ChatGPT_Extension#3]
![image](https://user-images.githubusercontent.com/12658912/209348083-237560af-036b-49c5-9594-308b957397ca.png)

**Comment by wong2** [comment]
Hi I think you open issue in the wrong repo

**Comment by wong2** [comment]
The right repo: https://github.com/wong2/chat-gpt-google-extension

The permission is needed to support Bing China as some user requested: https://github.com/wong2/chat-gpt-google-extension/issues/133

But I didn't know Chome would disable the extension when adding extra permissions.
