### ISSUE TITLE
OpenAi not supported in Vietnam

### ISSUE THREAD

**Issue by DrLuong** [kazuki-sf/ChatGPT_Extension#5]

**Comment by dandv** [comment]
This project is extremely simple: it [opens](https://github.com/kazuki-sf/ChatGPT_Extension/blob/main/popup.html#L10) https://chat.openai.com/chat in a popup. It does absolutely nothing else (why it exists, beats me; it's basically a bookmark).

So it won't help with OpenAI not being supported in Vietnam.

**Comment by kazuki-sf** [comment]
Thanks for clarifying, @dandv :)
