### ISSUE TITLE
Why does this project exist?

### ISSUE THREAD

**Issue by dandv** [kazuki-sf/ChatGPT_Extension#6]
This project is extremely simple: it [opens](https://github.com/kazuki-sf/ChatGPT_Extension/blob/main/popup.html#L10) https://chat.openai.com/chat in a popup. It does nothing else but [try to log you in](https://github.com/kazuki-sf/ChatGPT_Extension/blob/main/background.js).

It's basically a bookmark.

**Comment by kazuki-sf** [comment]
Yes! You're right! Thanks for clarifying!
